# This code is licensed from CircleCI to the user under the MIT license. See
# https://circleci.com/orbs/registry/licensing for details.
version: 2.1

description: |
  Simplify common tasks for building and testing Java projects using
  Gradle. Source: https://github.com/circleci-public/circleci-orbs

examples:
  gradle-workflow:
    description: Checkout, build, and test a Gradle project

    usage:
      version: 2.1

      orbs:
        gradle: circleci/gradle@1.0.0

      workflows:
        checkout-build-test:
          jobs:
            - gradle/test

        checkout-run_task:
          jobs:
            - gradle/run:
                command: build -x test

  custom-reports:
    description: Publish custom results and reports

    usage:
      version: 2.1

      orbs:
        gradle: circleci/gradle@1.0.0

      workflows:
        test-with-custom-reports:
          jobs:
            - gradle/test:
                test_command: myTests
                test_results_path: build/my-results/
                store_artifacts: build/my-reports/

executors:
  gradle:
    description: The docker container to use when running Gradle builds
    docker:
      - image: circleci/openjdk:11-jdk-stretch-node-browsers-legacy
    environment:
      # Disable fancy terminal updates
      TERM: dumb

commands:
  with_cache:
    description: |
      Run a set of steps with gradle dependencies cached.

      This command will first restore a cache of gradle dependencies, if one was
      saved by a previous build. The provided `steps` will then be executed, and
      if successful, then a fresh cache will be saved, if required.

      The contents of the `~/.gradle` directory is cached, which will substantially
      improve build times for projects with many dependencies.

      The cache-key is generated from any files named `build.gradle` that are
      present in the `working_directory`.
    parameters:
      steps:
        type: steps
    steps:
      - run:
          name: Generate Cache Checksum
          command: find . -name 'build.gradle' | sort | xargs cat | shasum | awk '{print $1}' > /tmp/gradle_cache_seed
      - restore_cache:
          key: gradle-{{ checksum "/tmp/gradle_cache_seed" }}-{{ checksum ".circleci/config.yml" }}
      - steps: << parameters.steps >>
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: gradle-{{ checksum "/tmp/gradle_cache_seed" }}-{{ checksum ".circleci/config.yml" }}

